---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: alpine/helm:3.2.1
    commands:
      - helm lint --strict .
  - name: package
    image: alpine/helm:3.2.1
    commands:
      - helm package . --destination .deploy
    when:
      branch:
        - master
      event:
        - push
  - name: release
    image: quay.io/helmpack/chart-releaser:v1.0.0-beta.1
    environment:
      CR_OWNER: ${DRONE_REPO_OWNER}
      CR_GIT_REPO: ${DRONE_REPO_NAME}
      CR_PACKAGE_PATH: .deploy
      CR_TOKEN:
        from_secret: CR_TOKEN
    commands:
      - cr upload
    when:
      branch:
        - master
      event:
        - push
  - name: checkout gh-pages
    image: alpine/git
    commands:
      - git fetch origin gh-pages
      - git checkout -t origin/gh-pages
    when:
      branch:
        - master
      event:
        - push
  - name: update index.yaml
    image: quay.io/helmpack/chart-releaser:v1.0.0-beta.1
    environment:
      CR_OWNER: ${DRONE_REPO_OWNER}
      CR_GIT_REPO: ${DRONE_REPO_NAME}
      CR_PACKAGE_PATH: .deploy
      CR_TOKEN:
        from_secret: CR_TOKEN
    commands:
      - cr index -i ./index.yaml -c https://rubasace.github.io/k8s-application-chart/
      - cat ./index.yaml
    when:
      branch:
        - master
      event:
        - push
  - name: push index.yaml
    image: plugins/gh-pages
    settings:
      username: rubasace
      password:
        from_secret: github_password
      pages_directory: .
    when:
      branch:
        - master
      event:
        - push
---
kind: signature
hmac: 51ca7298ecd3a697082ea502d932cd83419905114abb4edadd00b272d42dd152

...
