#TODO add description to fields and organize them better
deployment:
  replicas: 1
  containerPort: 8080
  imagePullSecrets: []
  image: ""
  tag: ""

service:
  port: 80

ingress:
  enabled: false
  class: nginx
  clusterIssuer: letsencrypt-prod
  oauth2Enabled: false
  oauth2AuthUrl: ""
  oauth2SigninUrl: ""
