apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: http
  selector:
    app: {{ .Release.Name }}
    serving: "true"